### ISSUE TITLE
Problems executing Qt Appimages

### ISSUE THREAD

**Issue by AnkeVisserJ** [linuxdeploy/linuxdeploy-plugin-qt#146] opened 2023-06-19 14:19 UTC
Hi,

on some systems, my AppImages (generated with linuxdeploy-plugin-qt) failed:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
`export QT_DEBUG_PLUGINS=1` showed me, that the system Qt libraries were loaded instead of the Qt libraries of the image. This was caused because LD_LIBRARY_PATH was set on this system and overwrites the adapted rpath of the AppImage. 

The cause of this error is hard to see for a normal user, so I changed the LD_LIBRARY_PATH in the apprun-hooks script to use the libraries of the AppImage. Any better idea?

Second issue:
```
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 2 (No such file or directory) on X server "localhost:10.0"
      after 416 requests (416 known processed) with 0 events remaining.
```
This happens when connecting with ssh. It doesn't happen with a Qt app that is created on the system.
The app starts using `export LIBGL_ALWAYS_INDIRECT=1`.

**Comment by TheAssassin** [comment] 2023-06-19 15:44
This is more a problem of (lib)linuxdeploy. I might migrate the issue later.

In my opinion, this is by design. `LD_LIBRARY_PATH` is supposed to always override application-specific or system settings. It should *never* be set "by default". It's a debugging feature, and a feature to make use of LGPL's "you must be able to use any ABI-compatible binary `.so` file when the library's license is LGPL" requirement.

GNU `ld`'s documentation also suggests that this is the way it should be done. System behavior can be configured in `/etc/ld.so.conf` and `ldconfig`, after all.

**Comment by AnkeVisserJ** [comment] 2023-06-19 21:53
I agree that LD_LIBRARY_PATH is handled the correct way, but I wonder if that's the best behaviour for AppImages. The user who executes the binary may not be administrator of the machine and may not even know anything about shared libraries or Qt. The user just executes a binary and gets an incomprehensible error message. 
Even if the user has set LD_LIBRARY_PATH manually (eg. for another program), it's unclear that that could effect the AppImage (without knowledge of the AppImage design). 
Anyway: maybe this issue will help a person who gets the same error message :smiley:

**Comment by TheAssassin** [comment] 2023-12-10 22:13
Thanks for your update. I guess we can close this issue. People using search engines will likely find this.

**Closed by TheAssassin** 2023-12-10 22:13 UTC
