### ISSUE TITLE
Failed to compile with CMake <= 3.7

### ISSUE THREAD

**Issue by kapitainsky** [linuxdeploy/linuxdeploy-plugin-qt#55] opened 2019-11-18 17:01 UTC
I would like to release AppImage on Raspberry Pi. I have managed successfully to compile from source linuxdeploy and linuxdeploy-plugin-appimage but linuxdeploy-plugin-qt gives me hard time.

when I run cmake . All process and result below:

```
$ git clone https://github.com/linuxdeploy/linuxdeploy-plugin-qt.git
$ cd linuxdeploy-plugin-qt
$ git submodule update --init --recursive
$ mkdir build && cd build
$ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at lib/linuxdeploy/CMakeLists.txt:28 (message):
  USE_CCACHE set, but could not find ccache


CMake Warning at lib/linuxdeploy/lib/linuxdeploy-desktopfile/CMakeLists.txt:20 (message):
  USE_CCACHE set, but could not find ccache

-- Found PythonInterp: /usr/bin/python (found version "2.7.13")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- [linuxdeploy-desktopfile] Test test_desktopfile is excluded from ALL, not adding as test
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.8")
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.28")
-- Found JPEG: /usr/lib/arm-linux-gnueabihf/libjpeg.so
-- Using bundled CImg library
-- Generating excludelist
-- [generate-excludelist.sh] downloading excludelist from GitHub
sha256sum: excludelist.h: No such file or directory
-- [generate-excludelist.sh] changes detected, updating excludelist.h
-- [linuxdeploy] Test test_appdir is excluded from ALL, not adding as test
-- [linuxdeploy] Test test_linuxdeploy is excluded from ALL, not adding as test
CMake Error at src/CMakeLists.txt:3 (target_link_libraries):
  Object library target "linuxdeploy-plugin-qt_util" may not link to
  anything.

-- Configuring incomplete, errors occurred!
```
Any idea what can prevent it from building?

**Comment by kapitainsky** [comment] 2019-11-18 17:52
Interestingly it happens only on raspbian based on stretch and works on one based on debian buster. There are still many stretch users out there (on raspberry pi at least) so my objective is to have AppImage released on stretch

**Comment by TheAssassin** [comment] 2019-11-18 17:53
@kapitainsky what CMake version are you using?

**Comment by kapitainsky** [comment] 2019-11-18 17:54
cmake version 3.7.2

**Comment by kapitainsky** [comment] 2019-11-18 17:55
I can  the build latest cmake and try. will report back

**Comment by TheAssassin** [comment] 2019-11-18 17:57
No, this should be recent enough. Can you please edit `generate-excludelist.sh` and add the line `set -x` right after the shebang?

**Comment by kapitainsky** [comment] 2019-11-18 18:02
with `set -x`:

$ cmake ..

cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at lib/linuxdeploy/CMakeLists.txt:28 (message):
  USE_CCACHE set, but could not find ccache


CMake Warning at lib/linuxdeploy/lib/linuxdeploy-desktopfile/CMakeLists.txt:20 (message):
  USE_CCACHE set, but could not find ccache


-- Found PythonInterp: /usr/bin/python (found version "2.7.13")
- Found PythonInterp: /usr/bin/python (found version "2.7.13")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- [linuxdeploy-desktopfile] Test test_desktopfile is excluded from ALL, not adding as test
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.8")
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.28")
-- Found JPEG: /usr/lib/arm-linux-gnueabihf/libjpeg.so
-- Using bundled CImg library
-- Generating excludelist
+ set -e
+ filename=excludelist.h
++ mktemp -t linuxdeploy-excludelist.h-XXXXXX
+ tempfile=/tmp/linuxdeploy-excludelist.h-nPG4Eh
++ basename /media/Samsung32G_01/Sources/linuxdeploy-plugin-qt/lib/linuxdeploy/src/core/generate-excludelist.sh
+ log_prefix='-- [generate-excludelist.sh]'
+ echo '-- [generate-excludelist.sh] downloading excludelist from GitHub'
-- [generate-excludelist.sh] downloading excludelist from GitHub
+ url=https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist
+ blacklisted=($(wget --quiet "$url" -O - | sed 's|#.*||g' | sort | uniq))
++ wget --quiet https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist -O -
++ sed 's|#.*||g'
++ sort
++ uniq
+ '[' ld-linux.so.2 == '' ']'
+ trap _cleanup EXIT
+ cat
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "ld-linux.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "ld-linux-x86-64.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libanl.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libasound.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libBrokenLocale.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libcidn.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libcom_err.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libc.so.6",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libdl.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libdrm.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libEGL.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libexpat.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libfontconfig.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libfreetype.so.6",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libfribidi.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libgbm.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libgcc_s.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libgdk_pixbuf-2.0.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libgio-2.0.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libglapi.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libGLdispatch.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libglib-2.0.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libGL.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libGLX.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libgmp.so.10",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libgobject-2.0.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libgpg-error.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libharfbuzz.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libICE.so.6",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libjack.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libm.so.6",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libmvec.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libnss_compat.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libnss_dns.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libnss_files.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libnss_hesiod.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libnss_nisplus.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libnss_nis.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libp11-kit.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libpango-1.0.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libpangocairo-1.0.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libpangoft2-1.0.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libpthread.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libresolv.so.2",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "librt.so.1",'
 for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libSM.so.6",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libstdc++.so.6",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libthai.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libthread_db.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libusb-1.0.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libutil.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libuuid.so.1",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libX11.so.6",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libxcb-dri2.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libxcb-dri3.so.0",'
+ for item in ${blacklisted[@]:0:${#blacklisted[@]}-1}
+ echo -e '    "libxcb.so.1",'
+ echo -e '    "libz.so.1"'
+ echo '};'
++ sha256sum excludelist.h
++ awk '{print $1}'
sha256sum: excludelist.h: No such file or directory
++ sha256sum /tmp/linuxdeploy-excludelist.h-nPG4Eh
++ awk '{print $1}'
+ '[' '' '!=' 6c1da60cf28ac5bedbcba4e808b00956646be22604fd68c8625fc5ba1991f4bc ']'
+ echo '-- [generate-excludelist.sh] changes detected, updating excludelist.h'
-- [generate-excludelist.sh] changes detected, updating excludelist.h
+ cp /tmp/linuxdeploy-excludelist.h-nPG4Eh excludelist.h
+ _cleanup
+ '[' -f /tmp/linuxdeploy-excludelist.h-nPG4Eh ']'
+ rm /tmp/linuxdeploy-excludelist.h-nPG4Eh
-- [linuxdeploy] Test test_appdir is excluded from ALL, not adding as test
-- [linuxdeploy] Test test_linuxdeploy is excluded from ALL, not adding as test
CMake Error at src/CMakeLists.txt:3 (target_link_libraries):
  Object library target "linuxdeploy-plugin-qt_util" may not link to
  anything.


-- Configuring incomplete, errors occurred!

**Comment by kapitainsky** [comment] 2019-11-18 18:18
on buster it looks like that:


```
$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at lib/linuxdeploy/CMakeLists.txt:28 (message):
  USE_CCACHE set, but could not find ccache

CMake Warning at lib/linuxdeploy/lib/linuxdeploy-desktopfile/CMakeLists.txt:20 (message):
  USE_CCACHE set, but could not find ccache

-- Found PythonInterp: /usr/bin/python (found version "2.7.16")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- [linuxdeploy-desktopfile] Test test_desktopfile is excluded from ALL, not adding as test
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11")
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.36")
-- Found JPEG: /usr/lib/arm-linux-gnueabihf/libjpeg.so (found version "62")
-- Using bundled CImg library
-- Generating excludelist
-- [generate-excludelist.sh] downloading excludelist from GitHub
/media/db_tc_1/Varia/Sources/linuxdeploy-plugin-qt/lib/linuxdeploy/src/core/generate-excludelist.sh: line 36: /tmp/linuxdeploy-excludelist.h-56nwOE: restricted: cannot redirect output
-- [linuxdeploy] Test test_appdir is excluded from ALL, not adding as test
-- [linuxdeploy] Test test_linuxdeploy is excluded from ALL, not adding as test
-- [linuxdeploy-plugin-qt] Test linuxdeploy-plugin-qt-tests is excluded from ALL, not adding as test
-- Configuring done
-- Generating done
-- Build files have been written to: /media/db_tc_1/Varia/Sources/linuxdeploy-plugin-qt/build
```

**Comment by TheAssassin** [comment] 2019-11-18 18:20
Inside that file, there's a few escaping issues. Aside from that, the "no such file or directory" doesn't matter at all, call it a warning that should go away after CMake generated the first `excludelist.h` time.

What CMake version have you used in the second attempt?

**Comment by kapitainsky** [comment] 2019-11-18 18:22
second attempt is on another raspberry pi running rasbian buster with cmake version 3.13.4

**Comment by TheAssassin** [comment] 2019-11-18 18:23
So there might indeed be an incompatibility that we haven't seen before...

I'll quickly try myself on the older stretch (well, not Raspbian for now, but a Debian container). Let's see what's going to happen.

**Comment by kapitainsky** [comment] 2019-11-18 18:29
I will build latest cmake and try on raspbian stretch - but later as waiting for whole latest Qt build to finish first.

**Comment by kapitainsky** [comment] 2019-11-18 19:23
FYI - I have tried on amd64 stretch  - the same issue (after I had also to force bundled CImg library).
But when I tried the same with the latest cmake (3.15.5) all worked fine.

**Comment by kapitainsky** [comment] 2019-11-18 19:26
now I am not familiar with linux enough to understand if it will have any negative issues if I build qt plugin with latest cmake.. will it affect AppImages compatibility etc?

**Comment by TheAssassin** [comment] 2019-11-18 19:26
Yep, I can reproduce the issue as well (just did). I started realizing what the issue is, and it's a CMake version incompatibility.

Now, there's exactly two things I can do. First, I can make it a `STATIC` library. That'll slightly increase compile times, but is more backwards compatible. Alternatively, I can track down which CMake version introduced support for this linking, and add a version compatibility mark, signalizing you'd need a newer CMake version.

I think I'm going to do the former.

**Comment by TheAssassin** [comment] 2019-11-18 19:27
No worries, it doesn't matter which CMake version you use to build your software (never has in all the years I've been using it).

**Comment by TheAssassin** [comment] 2019-11-18 19:29
By the way, there's a second occurrence in the code that causes a similar error message:

```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 201a827..505b2f5 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -1,4 +1,4 @@
-add_library(linuxdeploy-plugin-qt_util OBJECT util.cpp util.h)
+add_library(linuxdeploy-plugin-qt_util STATIC util.cpp util.h)
 target_include_directories(linuxdeploy-plugin-qt_util PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
 target_link_libraries(linuxdeploy-plugin-qt_util linuxdeploy_core args)
 
diff --git a/src/deployers/CMakeLists.txt b/src/deployers/CMakeLists.txt
index 6997fc0..71a2ac8 100644
--- a/src/deployers/CMakeLists.txt
+++ b/src/deployers/CMakeLists.txt
@@ -18,7 +18,7 @@ set(CLASSES
     GamepadPluginsDeployer
 )
 
-add_library(deployers OBJECT)
+add_library(deployers STATIC)
 
 target_link_libraries(deployers PUBLIC linuxdeploy_core linuxdeploy-plugin-qt_util)
 ```

**Comment by kapitainsky** [comment] 2019-11-18 19:31
kk. I am trying armhf with latest cmake. Then I can focus on AppImage story:)

**Comment by TheAssassin** [comment] 2019-11-18 19:33
@kapitainsky the problem has been fixed in code. You can `git pull` and build just fine. Thanks for bringing this CMake problem up!

**Closed** 2019-11-18 19:32 UTC

**Comment by kapitainsky** [comment] 2019-11-18 19:37
Thx! I can build now on raspbian stretch with default make. Works like a charm

**Comment by kapitainsky** [comment] 2019-11-18 20:09
not sure it is related by I always have

```
CMake Error at lib/linuxdeploy/cmake/Modules/FindCImg.cmake:21 (message):
  CImg.h not found
Call Stack (most recent call first):
  lib/linuxdeploy/src/core/CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
```

I just edit FindCImg.cmake and force "Using bundled CImg library" then all works. Should I create another issue or jsut ignore?

**Comment by TheAssassin** [comment] 2019-11-18 20:30
You can either install `cimg-dev` or call CMake with `-DUSE_SYSTEM_CIMG=Off`.

**Comment by kapitainsky** [comment] 2019-11-18 20:31
Kk. Clear
