### ISSUE TITLE
Some libraries and translations missing in AppImage

### ISSUE THREAD

**Issue by pbek** [linuxdeploy/linuxdeploy-plugin-qt#140] opened 2023-04-06 13:14 UTC
As suggested in https://github.com/probonopd/linuxdeployqt/issues/340#issuecomment-1499027540 I want to report a case of missing libraries and translations in the built AppImage.

In https://github.com/pbek/QOwnNotes/blob/b9d3d860874ffe1dff66c5b732922fe6e6f513e1/.github/workflows/build-release.yml#L130-L134 I had to resort to copying `/usr/plugins/iconengines` and `libqsvgicon.so`, as well as the translations from the qmake project file myself, because linuxdeploy missed those.

I didn't have to do that with https://github.com/probonopd/linuxdeployqt.

Are there maybe any pointers what could have went wrong?

**Comment by TheAssassin** [comment] 2023-04-06 13:19
Please provide a verbose build log (`-v0`), e.g., from CI, which should quickly tell us why the tool doesn't behave as expected. Usually, as soon as you [link to Qt's SVG module](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/master/src/qt-modules.h#L70), it should [deploy the `iconengines` directory](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/blob/19fae642faaefe9f05492256509028d906faa0c4/src/deployers/SvgPluginsDeployer.cpp).

**Comment by emericg** [comment] 2023-04-06 13:21
I *think* your extra plugin should just be something like `export EXTRA_QT_PLUGINS="svg;"`
I don't know about the translations.

**Comment by pbek** [comment] 2023-04-07 07:01
`export EXTRA_QT_PLUGINS="svg;"` already seemed to have helped with the SVG lib, thank you very much. So I can let go of https://github.com/pbek/QOwnNotes/blob/b9d3d860874ffe1dff66c5b732922fe6e6f513e1/.github/workflows/build-release.yml#L131.

The translation files from <https://github.com/pbek/QOwnNotes/blob/b9d3d860874ffe1dff66c5b732922fe6e6f513e1/.github/workflows/build-release.yml#L132> are still missing ...

This is the -v0 run: https://github.com/pbek/QOwnNotes/actions/runs/4630177779/jobs/8191411416#step:8:40
And this is the yielded AppImage: https://github.com/pbek/QOwnNotes/suites/12074809451/artifacts/635479247

**Comment by pbek** [comment] 2023-04-07 07:03
The config that build above AppImage: https://github.com/pbek/QOwnNotes/blob/c8998030b705ecad377847332e81ecd5ced21b34/.github/workflows/build-release-next.yml#L139-L143

**Comment by TheAssassin** [comment] 2023-04-07 15:46
@pbek well re. translations, you need to install these using CMake, as far as I can see. The plugin doesn't want to guessify how you load them from your application later on.

**Comment by TheAssassin** [comment] 2023-04-07 18:23
Not a bug as far as I can see from your build log. You don't link to Qt's SVG library. As far as I can see, one should link to it when the according icon engine should be used. Feel free to correct me if I'm wrong there. So far, the extra modules setting seems to do the trick. Closing for now.

**Closed by TheAssassin** 2023-04-07 18:23 UTC

**Comment by pbek** [comment] 2023-04-08 11:33
> well re. translations, you need to install these using CMake, as far as I can see. The plugin doesn't want to guessify how you load them from your application later on.

The path is specified in the qmake file: 
https://github.com/pbek/QOwnNotes/blob/1cbceefa42c70f5aad7e6064f52a97e49d90898b/src/QOwnNotes.pro#L403

I wonder how https://github.com/probonopd/linuxdeployqt managed to include them correctly... 🤔 

Thank you for all the help clearing up the build process!

**Comment by pbek** [comment] 2023-04-08 11:36
> Not a bug as far as I can see from your build log. You don't link to Qt's SVG library. As far as I can see, one should link to it when the according icon engine should be used. Feel free to correct me if I'm wrong there. So far, the extra modules setting seems to do the trick. Closing for now.

The SVG module is configured in 
https://github.com/pbek/QOwnNotes/blob/1cbceefa42c70f5aad7e6064f52a97e49d90898b/src/QOwnNotes.pro#L7.

https://github.com/probonopd/linuxdeployqt managed to detect the library as well, I again don't know how. 😁

**Comment by TheAssassin** [comment] 2023-04-08 11:57
@pbek linuxdeploy's current logic is basically "if any binary links to `libQtSvg.so*`, we assume it needs the SVG icon engine". If someone finds additional points when to deploy these icon engines (like linuxdeployqt apparently does), please share them!

**Comment by TheAssassin** [comment] 2023-04-08 11:59
> The SVG module is configured in
https://github.com/pbek/QOwnNotes/blob/1cbceefa42c70f5aad7e6064f52a97e49d90898b/src/QOwnNotes.pro#L7.

Indeed. Could you run `ldd <mymainbinary>` and verify it does link, please? I don't typically use qmake but CMake.

**Comment by pbek** [comment] 2023-04-08 12:07
No, it doesn't link to the svg library says ldd, but SVG icons (e.g. in QActions) don't seem to work correctly without the library added to the AppImage.

**Comment by pbek** [comment] 2023-04-08 12:12
> If someone finds additional points when to deploy these icon engines (like linuxdeployqt apparently does), please share them!

I don't know, other than trying to guess it from the CMakeLists.txt and qmake Project files. But since those files can be all around the place this is hard too..

My main issue was I didn't know how to add the missing library to `EXTRA_QT_PLUGINS` correctly...
