### ISSUE TITLE
Don't deploy `.so.debug` for Qt plugins

### ISSUE THREAD

**Issue by TheOneRing** [linuxdeploy/linuxdeploy-plugin-qt#110] opened 2022-05-25 08:25 UTC
```
[2022-05-25T07:51:29.140Z] [qt/stdout] Deploying shared library /home/appimage/Craft/BinaryFactory/linux-64-gcc/plugins/imageformats/libqtiff.so.debug (destination: /home/appimage/Craft/BinaryFactory/linux-64-gcc/build/kde/kdemultimedia/kdenlive/archive/usr/plugins/imageformats/)
[2022-05-25T07:51:29.140Z] [qt/stdout] Deploying dependencies for ELF file /home/appimage/Craft/BinaryFactory/linux-64-gcc/plugins/imageformats/libqtiff.so.debug
```

**Comment by bjorn** [comment] 2022-05-25 08:42
While described differently, the request is essentially a duplicate of #108.

**Closed** 2024-12-23 02:21 UTC
