### ISSUE TITLE
Crash building AnyMeal AppImage on Ubuntu Bionic 18.04.5 LTS

### ISSUE THREAD

**Issue by wedesoft** [linuxdeploy/linuxdeploy-plugin-qt#73] opened 2020-08-25 20:09 UTC
You can reproduce the error as follows:
```
git clone git@github.com:wedesoft/anymeal.git
cd anymeal
sudo apt-get install build-essential flex googletest librecode-dev libsqlite3-dev qt5-default qttools5-dev-tools
./autogen.sh
./configure --prefix=/usr
make clean
make -j `nproc`
make -f Makefile.appimage
```

The following error happens during execution of the last command:
```
[qt/stdout]   libGL.so.1  libGLX.so.0  libGLdispatch.so.0  libQt5Core.so.5  libQt5Gui.so.5  libQt5PrintSupport.so.5  libQt5Widgets.so.5  libX11.so.6  libXau.so.6  libXdmcp.so.6  libbsd.so.0  libc.so.6  libdl.so.2  libdouble-conversion.so.1  libfreetype.so.6  libgcc_s.so.1  libglib-2.0.so.0  libgraphite2.so.3  libharfbuzz.so.0  libicudata.so.60  libicui18n.so.60  libicuuc.so.60  libm.so.6  libpcre.so.3  libpng16.so.16  libpthread.so.0  librecode.so.0  librt.so.1  libsqlite3.so.0  libstdc++.so.6  libxcb.so.1  libz.so.1                     
munmap_chunk(): invalid pointer
Makefile.appimage:2: recipe for target 'appimage' failed
make: *** [appimage] Aborted (core dumped)
```

**Comment by TheAssassin** [comment] 2020-08-25 20:15
Duplicate of https://github.com/linuxdeploy/linuxdeploy/issues/143, which was transferred from this repository. Please do not open any more issues about the bug in this bug tracker.

**Closed by TheAssassin** 2020-08-25 20:15 UTC

**Comment by wedesoft** [comment] 2020-08-26 20:46
Ok, sorry. Didn't realise I was posting a duplicate. Thanks for your quick response.
